# .github/workflows/ci.yml
name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install -y gcc-multilib g++-multilib
        pip install cmake
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Test
      run: |
        cd build
        ctest --output-on-failure
